"""Add ip_address, mac_address, status and last_scan fields to CBSAsset

Revision ID: e522a150da11
Revises: 
Create Date: 2025-05-22 03:51:34.173810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e522a150da11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbs_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_scan', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbs_asset', schema=None) as batch_op:
        batch_op.drop_column('last_scan')
        batch_op.drop_column('status')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
